export const CREATE_LEAD_SUCCESS        = 'CREATE_LEAD_SUCCESS';
export const GET_USER_LIST_SUCCESS      = 'GET_USER_LIST_SUCCESS';
export const GET_MESSAGES_SUCCESS       = 'GET_MESSAGES_SUCCESS';
export const LOGIN_USER                 = 'LOGIN_USER';
export const LOGOUT_USER                = 'LOGOUT_USER';
export const SEND_MESSAGE_SUCCESS       = 'SEND_MESSAGE_SUCCESS';

//Forget Password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'

//get company location
export const UPDATE_CURRENT_LOCATION_REQUEST = 'UPDATE_CURRENT_LOCATION_REQUEST'
export const UPDATE_CURRENT_LOCATION_SUCCESS = 'UPDATE_CURRENT_LOCATION_SUCCESS'
export const UPDATE_CURRENT_LOCATION_ERROR = 'UPDATE_CURRENT_LOCATION_ERROR'


// Account
export const UPDATE_PROFILE             ='UPDATE_PROFILE';
export const GET_PROFILE                ='GET_PROFILE';

// APPOINTMENTS
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENTS_SUCCESS   = 'GET_APPOINTMENTS_SUCCESS';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';

// Jobs
export const GET_JOBS_SUCCESS           = 'GET_JOBS_SUCCESS';
export const GET_CUSTOMER_JOBS_SUCCESS = "GET_CUSTOMER_JOBS_SUCCESS"
export const UPDATE_JOB                 = 'UPDATE_JOB';

// Leads
export const GET_LEADS_SUCCESS           = 'GET_LEADS_SUCCESS';
export const UPDATE_LEAD                 = 'UPDATE_LEAD';

// TASKS
export const CREATE_TASKS_SUCCESS       = 'CREATE_TASKS_SUCCESS';
export const DELETE_TASKS_SUCCESS       = 'DELETE_TASKS_SUCCESS';
export const GET_TASKS_SUCCESS          = 'GET_TASKS_SUCCESS';
export const UPDATE_TASK_SUCCESS        = 'UPDATE_TASK_SUCCESS';

// Templates
export const GET_TEMPLATES              = 'GET_TEMPLATES'



// Estimates
export const GET_ESTIMATES_SUCCESS = "GET_ESTIMATES_SUCCESS"
export const UPDATE_ESTIMATE_STATUS_SUCCESS = "UPDATE ESTIMATE STATUS SUCCESS"
export const UPDATE_ESTIMATE_STATUS_ERROR = "UPDATE ESTIMATE STATUS ERROR"

// make payment

export const MAKE_PAYMENT_SUCCESS = "MAKE PAYMENT SUCCESS"
export const MAKE_PAYMENT_ERROR = "MAKE PAYMENT ERROR"



// get customer users
export const GET_CUSTOMER_USER_LIST_SUCCESS = "GET CUSTOMER USER LIST SUCCESS"
export const GET_CUSTOMER_USER_LIST_ERROR = "GET CUSTOMER USER LIST ERROR"

export const GET_PARTICULAR_USER_SUCCESS = "GET PARTICULAR USER SUCCESS"
export const SEND_TEXT_MESSAGE_SUCCESS = "SEND TEXT MESSAGE SUCCESS"


export const GET_ALL_EVENT_SUCCESS = "GET ALL EVENT SUCCESS"
